<?php

namespace App\Repositories;

use App\Models\Discount;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DiscountRepository extends EloquentRepository
{

    public function getModel()
    {
        return Discount::class;
    }

    public function getAll()
    {
        return DB::table('discounts')->leftJoin('products', 'discounts.product_id', '=','products.id')
            ->select('discounts.id', 'discounts.desc', 'discounts.discount_percent', 'discounts.price', 'discounts.active', 'products.name', 'products.image_path')
            ->orderBy('id', 'desc')
            ->get();
    }

    public function create(Request $request)
    {
        Discount::where('product_id', '=', $request['product_id'])->update([
            'active' => false,
        ]);
        parent::create($request); // TODO: Change the autogenerated stub
    }

    public function find($id)
    {
        return DB::table('discounts')->leftJoin('products', 'discounts.product_id', '=','products.id')
            ->select('discounts.*', 'products.name', 'products.image_path',)
            ->where('discounts.id', '=', $id)
            ->first();

    }

    public function update($id, Request $request)
    {
        Discount::where('product_id', '=', $request['product_id'])->update([
            'active' => false,
        ]);
        return parent::update($id, $request); // TODO: Change the autogenerated stub
    }


}
