<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Ramsey\Uuid\Type\Integer;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
           'name' =>'GEOMETRIC PRINT PENCIL SKIRT',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'100',
            'image_path'=>'https://static.zara.net/photos///contents/mkt/spots/ss22-north-woman-new/subhome-xmedia-05-3//w/364/IMAGE-large-portrait-24d34ba2-1472-4a30-9e4a-81dd48c427a0-default_0.jpg?ts=1643810424476',
        ]);
        DB::table('products')->insert([
            'name' =>'PLEATED TROUSERS',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'120',
            'image_path'=>'https://static.zara.net/photos///2022/V/0/1/p/6917/416/800/32/w/393/6917416800_1_1_1.jpg?ts=1644583657361',
        ]);
        DB::table('products')->insert([
            'name' =>'WOOL BLEND JACKET',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'100',
            'image_path'=>'https://static.zara.net/photos///2022/V/0/1/p/5514/679/500/32/w/284/5514679500_1_1_1.jpg?ts=1644585061836',
        ]);
        DB::table('products')->insert([
            'name' =>'COLOUR BLOCK JACKET',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'100',
            'image_path'=>'https://static.zara.net/photos///2022/V/0/1/p/0706/350/500/32/w/341/0706350500_2_1_1.jpg?ts=1644586222034',
        ]);
        DB::table('products')->insert([
            'name' =>'COLOUR BLOCK KNIT VEST',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'140',
            'image_path'=>'https://static.zara.net/photos///2022/V/0/1/p/9598/410/401/33/w/393/9598410401_1_1_1.jpg?ts=1644586430000',
        ]);
        DB::table('products')->insert([
            'name' =>'PUFFER JACKET WITH POCKETS',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'170',
            'image_path'=>'https://static.zara.net/photos//mkt/misc/watermarks/joinlife-ss19-v2/joinlife-large.svg?ts=1587055628000',
        ]);
        DB::table('products')->insert([
            'name' =>'PUFFER PARKA',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'120',
            'image_path'=>'https://static.zara.net/photos///2022/V/0/1/p/8281/415/401/34/w/341/8281415401_1_1_1.jpg?ts=1644586369315',
        ]);
        DB::table('products')->insert([
            'name' =>'GEOMETRIC PRINT PENCIL SKIRT',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'100',
            'image_path'=>'https://static.zara.net/photos///contents/mkt/spots/ss22-north-woman-new/subhome-xmedia-05-3//w/364/IMAGE-large-portrait-24d34ba2-1472-4a30-9e4a-81dd48c427a0-default_0.jpg?ts=1643810424476',
        ]);
        DB::table('products')->insert([
            'name' =>'FAUX LEATHER BLAZER',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'100',
            'image_path'=>'https://static.zara.net/photos///2022/V/0/1/p/0706/510/250/32/w/341/0706510250_1_1_1.jpg?ts=1644423713520',
        ]);
        DB::table('products')->insert([
            'name' =>'CONTRAST SATIN JACKET',
            'category_id'=>random_int(1,10),
            'description'=>'AT ZARA, WE ARE CONTINUOUSLY WORKING TO MAKE OUR BUSINESS MORE SUSTAINABLE. EVER SINCE WE SIGNED THE UNITED NATIONS (UN) GLOBAL COMPACT AND IMPLEMENTED OUR FIRST CODE OF CONDUCT IN 2001, OUR SOCIAL AND ENVIRONMENTAL OBJECTIVES HAVE BECOME MORE AMBITIOUS. WE HAVE DEVELOPED A ROADMAP WITH A HOLISTIC APPROACH THAT INCORPORATES BOTH PEOPLE-CENTRED CHALLENGES AND PLANET-CENTRED ONES.',
            'price'=>'100',
            'image_path'=>'https://static.zara.net/photos///2022/V/0/2/p/4344/747/712/2/w/248/4344747712_2_6_1.jpg?ts=1643797926271',
        ]);

    }
}
